### PR TITLE
Updated install_bioc to use git repositories instead of svn

### PR DESCRIPTION
**Pull request by rcannood**
This PR was first discussed in #1649. This is a duplicate PR from #1663, but updated to 1.13.4.

### CODE REVIEW

**Comment by rcannood** [comment]
Some travis tests are failed at this step:
``` R
  test_pkg <- create_in_temp("testGitHub")
  mock_use_github(test_pkg)
```

Correct me if I'm wrong, but I believe this is unrelated to the changes that I made.

**Comment by jimhester** [comment]
Thanks! I think the only thing missing is adding a note to NEWS.md with the change, mentioning the issue number and your GitHub username, then I can merge this.

**Comment by rcannood** [comment]
Done! I synced the fork, just to make sure there were no conflicts.

**Comment by jimhester** [comment]
Looks good, thanks!

**Pull request merged**
