### PR TITLE
Imported pkgbuild::find_rtools

### PR DESCRIPTION
**Pull request by jonthegeek**
Addresses issue #1909.

### CODE REVIEW

**Comment by jimhester** [comment]
Thanks @jonthegeek! But actually to fix this you need to do more than just import the function, you also need to export the function again, which is what we call this re-export.

An example of what you need is

https://github.com/r-lib/devtools/blob/bcdde3985c8220accc975e38236e5f802a0036b2/R/pkgbuild.R#L16-L18

**Comment by jonthegeek** [comment]
Sigh, I knew that. Too excited to get things done! Fixing it, sorry about that!

**Comment by jimhester** [comment]
no worries!

**Comment by jonthegeek** [comment]
@jimhester Actually exported now (tested by running devtools::find_rtools() in console, it isn't clear to me how to set up an automated test for this in particular, though).

**Comment by jimhester** [comment]
Thanks, this is great! Great job!

**Pull request merged**
