### PR TITLE
Minor fix to run_examples documentation.

### PR DESCRIPTION
**Pull request by DillonHammill**
Looks like examples in` \dontrun{}` are commented out when run is set to FALSE. Current docs suggest this behaviour is expected when `run = TRUE`.

### CODE REVIEW

**Comment by jimhester** [comment]
Relevant issues https://github.com/r-lib/pkgload/issues/107, https://github.com/r-lib/pkgload/issues/90

**Comment by jimhester** [comment]
Thanks for working on this!

**Comment by jimhester** [comment]
Thanks a bunch!

**Comment by DillonHammill** [comment]
No problem! Thanks for all the great work that you do for the R community. Really appreciate it!

**Pull request merged**
