### PR TITLE
Use rlang::inform() + glue() for messaging

### PR DESCRIPTION
**Pull request by hadley**
After doing this it occurred to me wonder if a cli function would've been better; let me know if you think it would be and I'll update.

### CODE REVIEW

**Comment by jimhester** [comment]
yeah a cli function would be preferred.

**Comment by hadley** [comment]
Which one?

**Comment by jimhester** [comment]
I guess it depends on the context of the particular message, the `cli_alert_()` family I guess.

**Comment by hadley** [comment]
Oh yeah, and then I can use inline markup and pluralisation as well. I'll take a look later today.

**Comment by jimhester** [comment]
This looks good to me, thanks!

**Pull request merged**
