### PR TITLE
Improve test coverage functionality

### PR DESCRIPTION
**Pull request by hadley**
This was never used correctly because we're passing the path to the package root, instead of the test directory. Additionally, based on https://github.com/hadley/testcoverage, they don't actually appear to be needed.

Fixes r-lib/testthat#1858

---

@jennybc my main scepticism here for the case of `test_coverage_active_file()`, I can't see how this can possibly work (even though it does). As far as I can tell, nothing in `test_coverage_active_file()` causes either `TESTTHAT_PKG` or the edition to be set correctly, but the tests still pass. 

...

Ooooh maybe the problem is that `test_coverage_active_file()` never actually reveals when the test fails.

...

Yes, that was the problem, and once I fixed that, it revealed that the snapshot paths weren't set up correctly, and it helped me understand why `local_test_directory()` is needed here, and why it works. I've added comments so hopefully this is less of a journey in the future.

### CODE REVIEW

**Comment by hadley** [comment]
@jennybc could you please interactively kick the tires of this PR with https://github.com/hadley/testcoverage and convince yourself that it all works as expected?

**Comment by jennybc** [comment]
Yes, I feel like my tire-kicking of https://github.com/hadley/testcoverage has been successful. 

But as I've used `test_coverage_active_file()`, which apparently I don't do much of in real life, I see this warning, which is coming from covr, I think. I suppose this is a side observation, as I don't think it has anything to do with recent changes in testthat or in this PR.

```
> test_coverage_active_file()
Warning message:
In mapply(FUN = f, ..., SIMPLIFY = FALSE) :
  longer argument not a multiple of length of shorter
```

**Review by jennybc — APPROVED** [review]
So, I think all is well here and in testthat, (but suspect there may be some buglet in covr).

**Comment by jennybc** [comment]
I made some other updates on `main` to eliminate some nuisance noise in `R CMD check`, so I merged that in here.

**Comment by hadley** [comment]
🥳 

Do you have a reprex for the recycling warning? I know I saw it multiple times in the workshop, but now I don't.

**Comment by jennybc** [comment]
I am also not seeing the `mapply()` warning any more 😐

**Pull request merged**
