### PR TITLE
Fix for #394

### PR DESCRIPTION
**Pull request by kevinushey**
Hi Hadley,

A simple fix for #394. We read in the `DESCRIPTION` and strip out any blank lines. Not so sure if you want to give a warning though.

### CODE REVIEW

**Comment by jacopone** [comment]
Hi all, apologies if this is not the right way to report this. 

I've installed Rcompression to solve this problem http://r.789695.n4.nabble.com/Decompressing-raw-vectors-in-memory-td4603202.html via install_github("omegahat/Rcompression"). 

It seems that the problem reported here also happens here https://github.com/omegahat/Rcompression/blob/master/DESCRIPTION, and I expected, maybe wrongly, this fix to solve it. 

Or should I remove blank lines from https://github.com/jacopone/Rcompression/blob/master/DESCRIPTION ? 

Thanks

**Comment by kevinushey** [comment]
I was just able to run `install_github("omegahat/Rcompression")` without issue, so at least it seems like the `devtools` side of things are in good shape (using the latest CRAN version of `devtools` + underlying packages).

That said, removing the trailing spaces as you have is an appropriate workaround if you're still seeing the issue.

**Comment by jacopone** [comment]
Yes that works well. The problem really happens when in a project using packrat:
* install_github("omegahat/Rcompression")
* packrat::snapshot()

Then when I restore() it breaks. The workaround I'm using so far is forking Rcompression, removing the spaces and using that version on my project. 

Thanks!

**Comment by kevinushey** [comment]
That seems like a fair workaround. Ultimately it seems like the bug would lie in Packrat though, not devtools (it has its own version of `install_github()` used during restore)

**Pull request merged**
